# fly.toml file generated for go-ssd-bot on 2023-01-30T20:00:27-05:00

app = "go-ssd-bot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "registry.gitlab.com/rrsharpe/go-ssd-bot-registry/go-ssd-bot"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true
