name: Go CI

on:
  push:
    branches:
      - main
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.19.5"
      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
      - name: Run build
        run: go build ./...
      - name: Test
        run: go test ./...
      - name: Login to GitLab Docker Registry
        uses: docker/login-action@v2
        with:
          registry: registry.gitlab.com
          username: rrsharpe
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            registry.gitlab.com/rrsharpe/go-ssd-bot-registry/go-ssd-bot
          tags: |
            type=raw,value={{date 'YYYYMMDD'}}
            type=raw,value=latest
      - name: Docker build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to Fly.io
        run: flyctl deploy --image registry.gitlab.com/rrsharpe/go-ssd-bot-registry/go-ssd-bot:latest
