name: Nightly Restart

on:
  schedule:
   - cron: "0 0 * * *"

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  restart:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Restart to update lists
        run: flyctl apps restart go-ssd-bot
